### ISSUE TITLE
Rerun benchmarks

### ISSUE THREAD

**Issue by Fdawgs** [kibertoad/nodejs-benchmark-tournament#10]
With the new Node versions added as part of #7 and #8 it'd be interesting to see what, if anything, has changed between Node 18 and 20!

**Comment by kibertoad** [comment]
@Fdawgs I'll add Node 21 to the mix this week and then rerun!

**Comment by kibertoad** [comment]
Still need to do this

**Comment by Fdawgs** [comment]
> Still need to do this

Whoops! Closed the wrong issue 😖

**Comment by Fdawgs** [comment]
@kibertoad looks like this is done?

**Comment by kibertoad** [comment]
not for everything yet!

**Comment by Fdawgs** [comment]
Probably needs Node 22 as well.
