### ISSUE TITLE
Use latest node versions

### ISSUE THREAD

**Issue by Fdawgs** [kibertoad/nodejs-benchmark-tournament#6]
First off, thanks for making this @kibertoad! I reference it quite a bit when looking to make optimisations in my own code.
The Node 16 and 18 versions are not the latest, and testing is being done on 19 (non-LTS) when 20 is soon to be LTS in 20 days.
Can these be updated?

Happy to make a PR for this!

**Comment by kibertoad** [comment]
go for it!
and thanks

**Comment by Uzlopak** [comment]
What is this?

**Comment by Fdawgs** [comment]
> What is this?

Benchmarks! https://github.com/kibertoad/nodejs-benchmark-tournament/blob/master/string-matching/_results/results.md
